#!/bin/bash

# Gets the first nodelist that will be used during the emulation
# This code has been mostly generated by GenAI.
# Parameter 1 - Amount of processes that will be spawned with mpirun
#====== Do not modify these values =======

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <numP>"
    exit 1
fi
numP=$1

# Convert into array
nodes=($(scontrol show hostname $SLURM_JOB_NODELIST))

# Convert Slurm CPU_PER_NODE
declare -a cpus_per_node
IFS=',' read -ra parts <<< "$SLURM_JOB_CPUS_PER_NODE"
for part in "${parts[@]}"; do
    if [[ "$part" =~ ([0-9]+)\(x([0-9]+)\) ]]; then
        count=${BASH_REMATCH[1]}
        nodes_count=${BASH_REMATCH[2]}
        for ((i=0; i<nodes_count; i++)); do
            cpus_per_node+=($count)
        done
    else # If it is only one node with this qty of cores
        cpus_per_node+=($part)
    fi
done

# Generate list
output=()
output2=()
process_count=0

for i in "${!nodes[@]}"; do
    node_name=${nodes[$i]}
    max_cores=${cpus_per_node[$i]}
    output+=("$node_name:$max_cores")
    process_count=$((process_count + max_cores))
    if [ $process_count -ge $numP ]; then
        break
    fi
done

#total_nodes="${#nodes[@]}"
#mid=$(( total_nodes / 2 ))
#rem=$(( total_nodes % 2 ))
#i=0
#while (( process_count < numP && i < mid )); do
#    node_name=${nodes[$i]}
#    max_cores=${cpus_per_node[$i]}
#    output+=("$node_name:$max_cores")
#    process_count=$((process_count + max_cores))
#    if [ $process_count -ge $numP ]; then
#        break
#    fi
#    i2=$(( i + mid + rem ))
#    node_name=${nodes[$i2]}
#    max_cores=${cpus_per_node[$i2]}
#    output2+=("$node_name:$max_cores")
#    process_count=$((process_count + max_cores))
#    i=$(( i + 1 ))
#done
#if [ $rem -ne 0 ] && [ $process_count -lt $numP ]; then
#    node_name=${nodes[$mid]}
#    max_cores=${cpus_per_node[$mid]}
#    output+=("$node_name:$max_cores")
#    process_count=$((process_count + max_cores))
#fi
#

string_output=$(echo "${output[*]}" "${output2[*]}"  | sed -e 's/ /,/g')
echo $string_output
