#!/bin/bash

# Gets the first nodelist that will be used during the emulation
# This code has been mostly generated by GenAI.
# Parameter 1 - Amount of processes that will be spawned with mpirun
#====== Do not modify these values =======

#cores=$2
#nodelist=$3

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <numP>"
    exit 1
fi
numP=$1

# Convert into array
nodes=($(scontrol show hostname $SLURM_JOB_NODELIST))

# Convert Slurm CPU_PER_NODE
declare -a cpus_per_node
IFS=',' read -ra parts <<< "$SLURM_JOB_CPUS_PER_NODE"
for part in "${parts[@]}"; do
    if [[ "$part" =~ ([0-9]+)\(x([0-9]+)\) ]]; then
        count=${BASH_REMATCH[1]}
        nodes_count=${BASH_REMATCH[2]}
        for ((i=0; i<nodes_count; i++)); do
            cpus_per_node+=($count)
        done
    else
        cpus_per_node+=($part)
    fi
done

# Generate list
output=()
process_count=0

for i in "${!nodes[@]}"; do
    node_name=${nodes[$i]}
    max_cores=${cpus_per_node[$i]}
    for ((j=0; j<max_cores && process_count<numP; j++)); do
        output+=("$node_name")
        ((process_count++))
    done
    if [ $process_count -ge $numP ]; then
        break
    fi
done

string_output=$(echo "${output[*]}" | sed -e 's/ /,/g')
echo $string_output
