[general]
resizes=1          ; Numero de redistribuciones
matrix_tam=1000    ; Tamaño en bytes de la matriz de computo
comm_tam=1000    ; Tamaño en bytes de los datos a comunicar en cada iteracion. Una sola vez
SDR=100000000       ; Tamaño en bytes a redistribuir de forma sincrona
ADR=100000000         ; Tamaño en bytes a redistribuir de forma asincrona  1000000000
AIB=3              ; Indica si las redistribuciones asíncronas se consideran terminadas para los padres
                   ;   cuando terminan de enviar (0), cuando terminan de recibir los valores (1)
                   ;   o usar comunicaciones punto a punto (2), o utilizar hebras(3)
CST=0            ; Indica como realizar el spawn. (0) Para el método baseline, (1) para el método
                 ; baseline con hilos, (2) para el método merge y (3) para el método merge
                 ; con hilos
CSS=0            ; Indica si el spawn se realiza con todos los procesos (0) o solo participa
                 ; el proceso raiz (1)
time=1           ; Tiempo necesario para realizar una iteracion
; end [general]


[resize0]              ; Grupo inicial(mpirun)
iters=10              ; Numero de iteraciones a realizar por este grupo
procs=2               ; Cantidad de procesos en el grupo
factor=1               ; Factor de coste 
physical_dist=node     ; Tipo de redistribución física de los procesos
;end [resize0]

[resize1]              ; Grupo de hijos 1
iters=20
procs=4
factor=0.5
physical_dist=node
;end [resize1]
