[general]
resizes=1
iter_stages=1
matrix_tam=100000
comm_tam=47192
SDR=0.0
ADR=0.0
AIB=0
CST=1
CSS=0
time=0.006
; end [general]
[stage0]
PT=3
bytes=0
t_stage=0.05
;end [stage0]
[stage1]
PT=3
bytes=0
t_stage=0.05
;end [stage0]
[resize0]
iters=10
procs=4
factor=1
physical_dist=cpu
;end [resize0]
[resize1]
iters=10
procs=8
factor=0.5
physical_dist=cpu
;end [resize1]
