[general]
resizes=1          ; Numero de redistribuciones
matrix_tam=1000    ; Tamaño en bytes de la matriz de computo
SDR=100       ; Tamaño en bytes a redistribuir de forma sincrona
ADR=100          ; Tamaño en bytes a redistribuir de forma asincrona  1000000000
AIB=0              ; Indica si las redistribuciones asíncronas se consideran terminadas para los padres
                   ;   cuando terminan de enviar (0) o cuando terminan de recibir los valores (1)
time=1           ; Tiempo necesario para realizar una iteracion

[resize0]              ; Grupo inicial(mpirun)
iters=10              ; Numero de iteraciones a realizar por este grupo
procs=2               ; Cantidad de procesos en el grupo
factor=1               ; Factor de coste 
physical_dist=cpu     ; Tipo de redistribución física de los procesos
;end [resize0]

[resize1]              ; Grupo de hijos 1
iters=20
procs=4
factor=0.5
physical_dist=cpu
